---
- name: Installing Drupal
  include: drush.yml
  with_items:
    - si: ["{{ profile }} --db-url=mysql://{{ mysql.user }}:{{ mysql.pass }}@{{ mysql.host | default('127.0.0.1') }}:{{ mysql.port | default('3306') }}/{{ databases.default }}"]

- include: ../environment/prepare.yml
