---
- name: Installing Drupal
  shell: "cd ../docroot && drush -y si {{ profile }} --db-url=mysql://{{ mysql.user }}:{{ mysql.pass }}@{{ mysql.host | default('127.0.0.1') }}:{{ mysql.port | default('3306') }}/{{ databases.default }} --uri={{ site_url }}"
  environment: env_vars

- include: ../prepare-environment.yml
