---
- name: Configure Apache
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_ports_configuration_items
  notify: restart apache

- name: Enable Apache mods
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: apache_mods_enabled
  notify: restart apache

- name: Disable Apache mods
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: apache_mods_disabled
  notify: restart apache

- name: Add Apache VHosts configuration
  template:
    src: "vhosts-{{ apache_vhosts_version }}.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

- name: Ensure that directory for SSL certificates for Apache exists
  file:
    path: "{{ apache_ssl_dir }}"
    state: directory

- name: Generate SSL certificates
  shell: "openssl req -x509 -nodes -days 365 -new -subj '/C=US/ST=Oregon/L=Portland/O=IT/CN={{ ansible_fqdn }}' -keyout {{ apache_ssl_dir }}/apache.key -out {{ apache_ssl_dir }}/apache.crt -extensions v3_ca creates={{ apache_ssl_dir }}/apache.crt"
