---
- name: Install Drush
  sudo: yes
  shell: "composer global require drush/drush:{{ cibox_composer_drush.version }} --no-interaction --no-ansi"
  sudo_user: "{{ cibox_composer_drush.user }}"

- name: Create symlinks
  sudo: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    state: link
  with_items:
    - src: "/home/{{ cibox_composer_drush.user }}/.composer/vendor/drush/drush/drush"
      dest: "/usr/local/bin/drush"
    - src: "/home/{{ cibox_composer_drush.user }}/.composer/vendor/bin/drush.complete.sh"
      dest: "/etc/bash_completion.d/drush"
