---
apt_repos:
  - ppa:ansible/ansible
  - ppa:chris-lea/node.js

apt_packages:
  - imagemagick
  - libmagickcore-dev
  - libmagickwand-dev
  - htop
  - vim
  - time
  - tree
  - make
  - apparmor-utils
  - python-software-properties
  - software-properties-common
  - rsync
  - libssl-dev
  - zlib1g-dev
  - ansible
  - rng-tools
  - python-passlib
  - cgroup-bin
  - git
  - ruby1.9.1
  - ruby1.9.1-dev
  - rubygems1.9.1
  - irb1.9.1
  - ri1.9.1
  - rdoc1.9.1
  - build-essential
  - libopenssl-ruby1.9.1
  - libssl-dev
  - zlib1g-dev
  - nodejs
