---
- name: Install APT keys for Google Chrome
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Adding Chrome APT repo to local database
  shell: sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install APT packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: selenium_packages

- include: dependencies.yml

- name: Create Xvfb service
  template:
    src: xvfb.j2
    dest: /etc/init.d/xvfb
    mode: 0750

- name: Enable Xvfb on boot
  shell: update-rc.d xvfb defaults
