---
- name: Clone Git repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ composer_dir }}/vendor/podarok/{{ item.name }}"
    version: "{{ item.branch }}"
  with_items: "{{ git_repos }}"

- name: Install PHP CodeSniffer standards
  file:
    src: "{{ composer_dir }}/{{ item }}"
    dest: "{{ composer_dir }}/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/{{ item | basename }}"
    state: link
  with_items: "{{ phpcs_standards }}"

- name: Install Node.js packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_packages }}"

- name: Update ruby alternatives for using ruby 1.9.1(3) version
  shell: "update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 --slave /usr/share/man/man1/ruby.1.gz ruby.1.gz /usr/share/man/man1/ruby1.9.1.1.gz --slave /usr/bin/ri ri /usr/bin/ri1.9.1 --slave /usr/bin/irb irb /usr/bin/irb1.9.1 --slave /usr/bin/rdoc rdoc /usr/bin/rdoc1.9.1"

- name: Install Gem packages
  shell: "gem install {{ item }}"
  with_items: "{{ gem_packages }}"
  ignore_errors: yes
