---
- name: Install
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin

- name: Rename PHAR file
  shell: cd /usr/local/bin/ && mv composer.phar composer

- name: Make Composer executable
  file:
    path: /usr/local/bin/composer
    mode: 0755

- name: Install packages
  shell: "composer global require {{ item.key }}:{{ item.value }} --no-interaction --no-ansi"
  become_user: "{{ ansible_user }}"
  with_dict: composer_packages

- name: Obtain user's home directory
  shell: "eval echo ~{{ ansible_user }}"
  register: user_home

- name: Add ~/.composer/vendor/bin to PATH
  lineinfile:
    dest: /etc/bash.bashrc
    line: "export PATH=$PATH:{{ user_home.stdout }}/.composer/vendor/bin"
    insertafter: BOF
