---
- name: Prepare project variable
  set_fact:
    jenkins_job: "{{ jenkins_job | upper }}"

- name: Stop service which could affect on 8080 port
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: ["nginx", "apache2"]

- include: repo.yml

- name: Download Jenkins
  get_url:
    url: "{{ jenkins_pkg_version }}"
    dest: ~/jenkins.deb
    mode: 440

- name: Install Jenkins
  shell: "dpkg -i ~/jenkins.deb"

- include: cli.yml
- include: plugins.yml

- name: Restore service
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: ["nginx", "apache2"]

- name: Adding Jenkins user to permitted groups
  user:
    name: "{{ jenkins_data.user }}"
    groups: shadow,adm
    append: yes

- name: Adding Jenkins user to nopasswd sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ jenkins_data.user }} ALL=(ALL) NOPASSWD:ALL"

- include: jobs.yml
