---
git_repos:
  Drupal:
    branch: 7.x-2.x
    repo: https://github.com/klausi/coder.git

  DrupalSecure:
    branch: master
    repo: http://git.drupal.org/sandbox/coltrane/1921926.git

  DrupalPractice:
    branch: 7.x-1.x
    repo: https://github.com/klausi/drupalpractice.git

  Security:
    branch: master
    repo: https://github.com/podarok/phpcs-security-audit.git

  Symfony2:
    branch: master
    repo: https://github.com/podarok/Symfony2-coding-standard.git

  WordPress:
    branch: master
    repo: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git

npm_packages:
  - jshint

gem_packages:
  - scss-lint
