---
- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

# Setup/install tasks.
- name: Set up PHP 5.6
  action: apt_repository repo='ppa:ondrej/php5-5.6' state=present
  ignore_errors: yes

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  ignore_errors: yes

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ php_packages }}"
  notify: restart webserver

# Configure PHP.
- include: configure.yml
